### ISSUE TITLE
Question: docker install + config

### ISSUE THREAD

**Issue by pergolafabio** [mancioshell/risco-mqtt-home-assistant#1]
Hi @mancioshell , i wanted to try out your system instead of Luca, i dont think he already implemented the new REST API in his system
i like it a lot, but i miss one feature in his version, and thats the delay when you arm from a hardware panel, seems that state is only passed with a hug delay lilke 2 mins

thats not happening if you use the app...

but anyway

how can i use your system? is it possible to run it as a docker? how/where can i point to that config file? i dont see that in the documentation? or is a docker install not possible?

or can it be used as an add-on /custom in HA? that would be really nice offcourse...!! :)

**Comment by d4icon** [comment]
Hi,
I am also very interested in this issue, @mancioshell 

I am trying to adapt this to use it in HASSIO, but I am not able for now.

Could you help us?

thanks

**Comment by pergolafabio** [comment]
ok, @mancioshell  , testing your stuff
really great! my binary sensors are switching instantly!! thats so cool
now i can actually use them as movement sensors to turn on light and stuff like that

great job!

**Comment by d4icon** [comment]
> ok, @mancioshell , testing your stuff
> really great! my binary sensors are switching instantly!! thats so cool
> now i can actually use them as movement sensors to turn on light and stuff like that
> 
> great job!

You can install in hassio?
How?

**Comment by pergolafabio** [comment]
no, i install on my test ubuntu server

**Comment by mancioshell** [comment]
> > ok, @mancioshell , testing your stuff
> > really great! my binary sensors are switching instantly!! thats so cool
> > now i can actually use them as movement sensors to turn on light and stuff like that
> > great job!
> 
> You can install in hassio?
> How?

The advice to use this package with home assistant is to use Raspbian on raspberry and install docker on it. Then

- run hassio as [docker container](https://www.home-assistant.io/docs/installation/docker/). 
- run mqtt server as docker container (maybe you could uese [eclipse-mosquitto](https://hub.docker.com/_/eclipse-mosquitto))
- run this project as docker container. risco-mqtt-home-assistant supports mqtt auto discovery so you could use in your hassio docker environment.

**Comment by pergolafabio** [comment]
Hi @mancioshell , do you have a docker image available for this project? i am the npx, works verry stable

so wanna load it on portainer now :)

**Comment by rob1981forest** [comment]
Hi @pergolafabio - just saw your post on luca's page regarding this one - thanks ! 

Did you figure out how to get this working in a synology docker ?

**Comment by pergolafabio** [comment]
I installed it for now on Ubuntu docker...

Works very good, instant state changing, also sensors... Best project untill now

**Comment by rob1981forest** [comment]
Sounds great, but no idea how I would do Ubuntu docker !!! Looks like I will have to wait for Luca one to move forward......thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pergolafabio** [comment]
You don't need docker to run it, just run it with that npx command...

Docker is not needed

**Comment by rob1981forest** [comment]
But I need to install something like centos or Ubuntu somewhere ?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pergolafabio** [comment]
Yeah, you need a Linux system ;)

But you have Synology? Just install a node container? Or Ubuntu system there? It's as easy to install the Luca 

Then you have your docker also ;)

**Comment by rob1981forest** [comment]
Yeah I have Synology but I'm a Windows man for 20 years and Linux is still very confusing for me......so run Ubuntu in my virtual machine manager ? Seems a lot of resource to use up just on this......maybe a will as a test then.....thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pergolafabio** [comment]
I am also windows, believe me, I need to Google for every command ;)

It doesn't take that many resources.. 

Find an image "node" on your docker , that will do...

Then just follow instructions, those 2 commands and your config file

**Comment by pergolafabio** [comment]
just did it myself
so opened docker, installed this container image :  node:latest
start that container, install the package , point your config.json like you do with the luca version
then  run the container with the npx command

done!

image size is about 1 gb

**Comment by rob1981forest** [comment]
Brilliant, thanks for the help......will try it out and let you know.....thanks again

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pergolafabio** [comment]
are you using hass.io ? then you can also user the "portainer" addon
i use that one to create dockers , not using my synology anymore

also if you install ha-dockermon, you can access other containers with REST
so i have also now created a template switch, to restart the docker if needed from within lovelace

**Comment by rob1981forest** [comment]
I'm using home assistant core........I have been messing with the hassio APK file that someone made but still using original docket setup as it's been working well.

Don't fancy changing it all as my family will go nuts when if things break !!!!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pergolafabio** [comment]
ah ok ;)

well, addons are so super easy

**Comment by rob1981forest** [comment]
do i need to map volumes to a location on my synology - dont seem to know where i should put this json file ?

**Comment by pergolafabio** [comment]
yes, you can mount OR create it in the workdir ...

/usr/src/app/config.json

**Comment by rob1981forest** [comment]
Mmm, making progress but getting file config.json does not exist when running the npx command....

I have mapped the config.json location you said to a place on my Synology but no luck...

Any ideas ?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pergolafabio** [comment]
no, this : /usr/src/app/config.json
thats the place on the docker dir, it you have configured it as workmap

**Comment by rob1981forest** [comment]
Yeah, that's what I think I've done !!! Mapped it to my local 'docker/node/config.json'

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pergolafabio** [comment]
but have you alsos setup that work dir? otherwise it doesnt work, or it doesnt know where to look

**Comment by pergolafabio** [comment]
indeed, if i dont define a working dir, then i also have config.json not found message
i can setup a working dir in portainer; you not?
otherwise , point it maybe direct in the "risco-mqtt-home-assistant" folder where its installed
or just create that config.json manually without binding for now ...

**Comment by rob1981forest** [comment]
Thanks, maybe yes......I'll try and not do the mapping for now to keep things simple.....thanks for the help

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rob1981forest** [comment]
me again, still cant get this working. no idea how to get the JSON into the node.js container either via mapping or in it........is turning this into a full docker hard @mancioshell ? It seems a great development from what Luca made but im finding it hard to figure out !!

**Comment by pergolafabio** [comment]
well, there are only 3 places where you can make it
in portainer => i can define  a workdir => you dont have that
try to make it in : risco-mqtt-home-assistant folder 
or try to make it in the root, where you  enter if you ssh in it
i think when you start the docker with that npx command, since there is no path defined, it will search for the json file on the place from where you start the npx command

**Comment by rob1981forest** [comment]
in synology docker you have all the 'Environment Variables' and in here i did create a 'WORKDIR' which i mapped to my local folder but still no luck ! is this where i would set the WORKDIR ?

**Comment by pergolafabio** [comment]
no, i didnt touch/definre environment at all
i can define the workdir on some other place, here some screens : 

https://www.dropbox.com/s/jteudvoe31e1u24/portainer1.JPG?dl=0
https://www.dropbox.com/s/9iau5rcxcl437fv/portainer2.JPG?dl=0
https://www.dropbox.com/s/5lwl3rlmk3uis98/portainer3.JPG?dl=0

**Comment by rob1981forest** [comment]
i dont think synology has the option to set a WORKDIR

did find this when googling though - i think this would convert this into a docker ?

https://nodejs.org/de/docs/guides/nodejs-docker-webapp/

**Comment by pergolafabio** [comment]
yeah, i have found that tutorial too, i used that one also to create it on my ubuntu test system :)

but i have started again, directly from an already excisting docker , the end result is the same :)

**Comment by pergolafabio** [comment]
dont give up! i am really impressed by this one
using the pir sensors now for automations like turning on lights in the morning, spotify on ...
also, this one is more stable then luca, the one from luca, i had to reboot ocen a few days, seems it didnt poll anymore... so therefore my automations based on arm / disarm didnt work anymore
also this one, the state of arm/disarm is almost instant, no delay anymore

much impressed!

**Comment by rob1981forest** [comment]
Sounds good......I really want pir to trigger lights as you know but for me the Luca one has been rock solid......my container been up 62 days at moment.......so my only issue with Luca one is the delay in pir response which I can live with .........I've moved to node red so trying to learn that, also studying AWS for work so time in short supply at moment !!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by francois-dotnet** [comment]
I have been trying to get this working, read all the comments and tried for hours! 
System: Ubuntu server 18.04 on Pi4. I have it working from the command-line (npx risco-mqtt-home-assistant in /home/ubuntu/riscomqttapp/) and it auto-discovers in HA. But I cannot for the life of me get it to work in Docker. I have installed Portainer - see screenshot below of my config. 

I keep getting: "file config.json does not in json format". As far as I can tell it is the same config.json file that works from the command line. 

Any help will be appreciated. Thanks.

![Capture1](https://user-images.githubusercontent.com/61493103/77838397-d233a880-7173-11ea-9874-9c90f0f638a6.JPG)
![Capture2](https://user-images.githubusercontent.com/61493103/77838400-d52e9900-7173-11ea-8409-293e06f76474.JPG)
![Capture3](https://user-images.githubusercontent.com/61493103/77838399-d4960280-7173-11ea-86fb-442cac0c9127.JPG)

**Comment by pergolafabio** [comment]
You need to specify "bind" type, make sure that button is selected, then you specifybalso the json file on the docker... Now you only selected it in your host...

**Comment by francois-dotnet** [comment]
Got it to work it seems but I had no clue what bind type was referred to?
 
I got it to work by doing a git clone as per lucacalcaterra installation, created a config.json file, then created a docker image: "docker build --tag risco-mqtt-home-assistant". Then with the help of Portainer created a container using the previously created image: no additional advance container settings with commands, volumes, etc necessary. 

Seems to be working - crossing fingers.

**Comment by pergolafabio** [comment]
Good job ;)

In my case, it's working better then luca version... No restarts needed, and also sensors are also changing instant

**Comment by francois-dotnet** [comment]
> Good job ;)
> 
> In my case, it's working better then luca version... No restarts needed, and also sensors are also changing instant

Looking forward to working with it. Is it read-only or can you send commands too?

**Comment by rob1981forest** [comment]
@pergolafabio

Managed to get this working now in docker for Synology and it auto starts on boot following a few tweaks ...
 As you say .....it's good.

However one zone won't show up but see another thread about zone names with multiple spaces which could be my issue.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pergolafabio** [comment]
> > Good job ;)
> > In my case, it's working better then luca version... No restarts needed, and also sensors are also changing instant
> 
> Looking forward to working with it. Is it read-only or can you send commands too?

Offcourse you can send commands ;)

**Comment by DanVer1758** [comment]
For those who are interested, hereby a snippet of my docker-compose:

>    risco-mqtt-home-assistant:
>     container_name: Risco-mqtt-bridge
>     restart: unless-stopped
>     image: node:latest
>     volumes:
>       - type: bind
>         source: /home/ubuntu/docker/risco-mqtt-home-assistant/config.json
>         target: /config.json
>       - /etc/localtime:/etc/localtime:ro
>       - /etc/timezone:/etc/timezone:ro
>     command: >
>       bash -c "npx risco-mqtt-home-assistant"
>     depends_on:
>       - mosquitto

This runs on a ubuntu 20.04 VM, obviously there are some tweaks to be done ;-) @mancioshell Fantastic job, buddy!

**Comment by yuvalmesika** [comment]
> dont give up! i am really impressed by this one
> using the pir sensors now for automations like turning on lights in the morning, spotify on ...
> also, this one is more stable then luca, the one from luca, i had to reboot ocen a few days, seems it didnt poll anymore... so therefore my automations based on arm / disarm didnt work anymore
> also this one, the state of arm/disarm is almost instant, no delay anymore
> 
> much impressed!

@pergolafabio, does the pie sensor status changed even if the alarm system is not in armed?

I have the risco commpact panel. And the pir sensors status is always 0.

**Comment by pergolafabio** [comment]
yeah, they are changing, because i am use the to control spotify when i come in a specific zone :)

**Comment by rob1981forest** [comment]
I agree, tool me a while to figure out how to install but once working rock solid and I use pir for light turn on.....great job.....see no reason for an official API as this one does the business

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pergolafabio** [comment]
Official api is always better ;-) when risco changes something, this what we use now, won't work anymore... That's not the case with official... And probably we can do more then , like outputs, cameras, users ...

**Comment by yuvalmesika** [comment]
I guess because I have a different panel, the status of the sensors is not updated,
My panel is this:
https://www.riscogroup.com/uk/products/product/52438
and this version with the partitions support does work for me (the partitions are always returned as null, so I changed the code to support my panel)
Are you guys using the LightSYS or Agility?

**Comment by pergolafabio** [comment]
i am using lightsys

i am testing at the moment the official risco component for HA , no sensors right now, we have to wait until 115.x
maybe he can test and see for you if those sensors are possible
