### ISSUE TITLE
Doesnt update anymore after a few min

### ISSUE THREAD

**Issue by pergolafabio** [mancioshell/risco-mqtt-home-assistant#2]
Hey,

tried out your package, it starts up perfect, creates the alarm panel and some binary sensors in HA
for the moment just testing the binary sensors
they go to on/off state when i walking before them, the state changes almost instantly
looks perfect

untill some min later... they dont update anymore
seems its stuck?

how can i troubleshoot this? the package command line is still fillint up with lines like...
published alarm status ... on partition xx

so no error there
maybe polling interval to quick? i have now the default 500 setup
thnx in advance

**Comment by pergolafabio** [comment]
oww, i did configure 500 , maybe it needs to be 5000 ? maybe i was just polling to quick :)

**Comment by pergolafabio** [comment]
ok, seems 5000 is more stable, up and running for more then 12 hours now
just a question @mancioshell 
is that timer only for polling the arm status? or is it also for polling the dect sensors?
i want to use the sensors also for motion control to turn on light... so 5000 ms is too long
thats why i wanted to know if that timer is also used for retrieving the state of de dects ? if yes, then i need to play with it... maybe lower it down to like 2000 / 1000 ? not sure whats possible?

**Comment by mancioshell** [comment]
> ok, seems 5000 is more stable, up and running for more then 12 hours now
> just a question @mancioshell
> is that timer only for polling the arm status? or is it also for polling the dect sensors?
> i want to use the sensors also for motion control to turn on light... so 5000 ms is too long
> thats why i wanted to know if that timer is also used for retrieving the state of de dects ? if yes, then i need to play with it... maybe lower it down to like 2000 / 1000 ? not sure whats possible?

Hi @pergolafabio. interval-polling configuration is the polling frequency for all the interaction with RISCO Rest API, so for alarm status and dect sensors status. 
It should be an enhancement to make available 2 interval polling frequency, one for arm status and one for dect sensore. I'll try to work about this feature as soon as possible.
Anyway, for my personal experience, i have seen that 5000 ms is a good compromise also for dect sensor and alarm status.

**Comment by pergolafabio** [comment]
Ok, thnx for feedback, really like this one, rest API is indeed better then luca version...
You gonna make an add-on for HA?

**Comment by mancioshell** [comment]
> Ok, thnx for feedback, really like this one, rest API is indeed better then luca version...
> You gonna make an add-on for HA?

No i don't think for now. Even if in the past i have developed in python, i have not so much time to create a custom integration for HA at the moment.

**Comment by pergolafabio** [comment]
Ok, maybe next time in July, when official API is going to be released ;)

**Comment by pergolafabio** [comment]
ok, playing with the seconds, seems 3500 is also stable for the PIR sensors
but i have configured my binar sensors now as below,  i dont shut them off anymore with the "idle" payload...
because, am i correct if i say : if you walk before a pir sensor, then you have offcourse a triggerd and an idle event ... when you are polling, are you sending the last state? or both ? cause if you sending last one, we can "miss" an event? so to turn on a light, this is not appropriate to wait for the nex poll 
i think its better  to define the sensor like this : 
```

  - platform: mqtt
    name: Risco 1
    state_topic: "riscopanel/alarm/0/sensor/0/status"
    payload_on: "triggered"
    #payload_off: "idle" 
    off_delay: 5
```
